/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:13fb3010-ef80-49c0-b051-4deb96772d69",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WTN2JYvpE",
    "aws_user_pools_web_client_id": "61m2ddbg42r9p5vc81dcanvad1",
    "oauth": {}
};


export default awsmobile;
