/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:13fb3010-ef80-49c0-b051-4deb96772d69",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WTN2JYvpE",
    "aws_user_pools_web_client_id": "61m2ddbg42r9p5vc81dcanvad1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pkppqiihrzamziw6bykhat3qie.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pbji7tz4ifcfllzjw4affbtan4"
};


export default awsmobile;
